CREATE TABLE accounts(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100),
  account_id VARCHAR(100),
  secret_token VARCHAR(100),
  website VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );


  CREATE TABLE destination(
  id INT AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(100),
  account_id VARCHAR(100),
  Method VARCHAR(100),
  Headers JSON,
  status VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );